ServerEvents.recipes(event => {
    
	event.remove({ id: 'biomancy:crafting/primordial_cradle' })

    // event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
    //     .input('3x biomancy:impermeable_membrane', 'biomancy:mob_gland', '4x biomancy:flesh_bits', '4x biomancy:tough_fibers')
    //     .itemOutput('biomancy:storage_sac')
    //     .itemOutput('minecraft:glass_bottle')
    // event.recipes.summoningrituals.altar('minecraft:bone')
    //     .input('3x biomancy:tough_fibers', '4x biomancy:flesh_bits')
    //     .itemOutput('2x biomancy:flesh_spike')
    // event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
    //     .input('2x biomancy:tough_fibers', '8x biomancy:flesh_bits', '2x architects_palette:nether_brass_ingot', 'minecraft:chest')
    //     .sacrifice('pig')
    //     .itemOutput('biomancy:fleshkin_chest')
    //     .itemOutput('minecraft:glass_bottle')
    // event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
    //     .input('chestcavity:iron_scrap', '4x biomancy:elastic_fibers', '8x biomancy:flesh_bits', 'architects_palette:nether_brass_ingot')
    //     .sacrifice('pig')
    //     .itemOutput('2x biomancy:maw_hopper')
    //     .itemOutput('minecraft:glass_bottle')
    // event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
    //     .input('4x biomancy:elastic_fibers', '6x biomancy:flesh_bits')
    //     .sacrifice('pig')
    //     .itemOutput('biomancy:tongue')
    //     .itemOutput('minecraft:glass_bottle')

    event.recipes.summoningrituals.altar('biomancy:fleshkin_chest')
        .input('8x kubejs:bottle_of_blood', '16x biomancy:flesh_bits', '4x biomancy:mob_gland', '8x biomancy:elastic_fibers', '8x biomancy:flesh_spike', '4x architects_palette:nether_brass_ingot')
        .sacrifice('villager')
        .itemOutput('biomancy:primordial_cradle')
        .itemOutput('8x minecraft:glass_bottle')
})