ServerEvents.recipes(event => {
    event.recipes.summoningrituals.altar('minecraft:beetroot_soup')
        .input('2x #biomancy:raw_meats', '1x biomancy:bone_fragments')
        .itemOutput('minecraft:bowl')
        .mobOutput('zombie')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x farmersdelight:cooked_rice', '2x chestcavity:iron_scrap')
        .sacrifice('zombie')
        .mobOutput('zombie_villager')
        .itemOutput('minecraft:glass_bottle')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x #biomancy:raw_meats', 'minecraft:bone')
        .itemOutput('minecraft:glass_bottle')
        .mobOutput(
            SummoningOutput.mob('zombie')
                .count(2)
        )
    
    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x biomancy:bone_fragments', 'minecraft:arrow')
        .itemOutput('minecraft:glass_bottle')
        .mobOutput(
            SummoningOutput.mob('skeleton')
                .count(2)
        )

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('#minecraft:wool', 'minecraft:bone')
        .itemOutput('minecraft:glass_bottle')
        .mobOutput('spider')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('4x #minecraft:leaves', 'minecraft:bone')
        .itemOutput('minecraft:glass_bottle')
        .mobOutput('creeper')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x biomancy:bile', 'biomancy:exotic_dust', 'dungeonsdelight:spider_extract')
        .itemOutput('2x minecraft:glass_bottle')
        .sacrifice('zombie')
        .mobOutput('enderman')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x biomancy:volatile_gland', '4x biomancy:bone_fragments', 'dungeonsdelight:spider_extract')
        .itemOutput('2x minecraft:glass_bottle')
        .sacrifice('skeleton')
        .mobOutput('blaze')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('dungeonsdelight:stained_scrap', 'minecraft:egg')
        .itemOutput('minecraft:skeleton_spawn_egg')
        .itemOutput('minecraft:glass_bottle')
        .sacrifice('skeleton')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('dungeonsdelight:stained_scrap', 'minecraft:egg')
        .itemOutput('minecraft:zombie_spawn_egg')
        .itemOutput('minecraft:glass_bottle')
        .sacrifice('zombie')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('dungeonsdelight:stained_scrap', 'minecraft:egg')
        .itemOutput('minecraft:spider_spawn_egg')
        .itemOutput('minecraft:glass_bottle')
        .sacrifice('spider')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('dungeonsdelight:stained_scrap', 'minecraft:egg')
        .itemOutput('minecraft:creeper_spawn_egg')
        .itemOutput('minecraft:glass_bottle')
        .sacrifice('creeper')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x dungeonsdelight:stained_scrap', 'minecraft:egg', 'chestcavity:heart')
        .itemOutput('minecraft:enderman_spawn_egg')
        .itemOutput('minecraft:glass_bottle')
        .sacrifice('enderman')

    event.recipes.summoningrituals.altar('kubejs:bottle_of_blood')
        .input('2x dungeonsdelight:stained_scrap', 'minecraft:egg', 'chestcavity:heart')
        .itemOutput('minecraft:blaze_spawn_egg')
        .itemOutput('minecraft:glass_bottle')
        .sacrifice('blaze')
})