ServerEvents.recipes(event => {
	event.remove({ output: /thermal:.*augment.*/ })

    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
    event.recipes.thermal.smelter([], [])
})