ServerEvents.recipes(event => {
	event.remove({ id: 'biomancy:crafting/primordial_cradle' })
	event.remove({ id: 'biomancy:crafting/decomposer' })
	event.remove({ id: 'biomancy:crafting/digester' })
	event.remove({ id: 'biomancy:crafting/bio_forge' })
	event.remove({ id: 'biomancy:bio_forging/decomposer' })
	event.remove({ id: 'biomancy:bio_forging/digester' })
	event.remove({ id: 'biomancy:bio_forging/bio_forge' })
	event.remove({ id: 'biomancy:bio_forging/bio_lab' })
	event.remove({ id: 'biomancy:bio_forging/injector' })
	event.remove({ id: 'biomancy:bio_forging/extractor' })
	event.remove({ id: 'biomancy:bio_forging/caustic_gunblade' })
	event.remove({ id: 'biomancy:bio_forging/impaler' })
	event.remove({ id: 'biomancy:bio_forging/thorn_shield' })
	event.remove({ id: 'biomancy:bio_forging/ravenous_claws' })
	event.remove({ id: 'biomancy:bio_forging/maw_hopper' })
	event.remove({ id: 'biomancy:bio_forging/tongue' })
	event.remove({ id: 'biomancy:bio_forging/fleshkin_chest' })
	event.remove({ id: 'biomancy:bio_forging/active_muscle' })
	event.remove({ id: 'biomancy:bio_forging/chrysalis' })
	event.remove({ id: 'biomancy:bio_forging/storage_sac' })
	event.remove({ id: 'biomancy:bio_forging/flesh_spike' })
	event.remove({ id: 'biomancy:bio_forging/phantom_membrane' })
	event.remove({ id: 'biomancy:bio_forging/impermeable_membrane' })

    event.recipes.biomancy.bio_forging(['4x industrialforegoing:pink_slime_ingot', '2x architects_palette:entrails', 'kubejs:biological_core', 'chestcavity:ender_liver', 'biomancy:creator_mix'], 'biomancy:bio_lab', 'biomancy:machines', 150)
    event.recipes.biomancy.bio_forging(['4x #forge:plates/chitinsteel', '2x architects_palette:entrails', '4x kubejs:mineral_brick', 'chestcavity:heart', 'biomancy:living_flesh'], 'kubejs:living_tool_smithing_template', 'biomancy:tools', 75)
    
    event.recipes.biomancy.bio_forging(['chestcavity:mana_reactor', '4x kubejs:dense_muscle', '2x industrialforegoing:pink_slime_ingot', '4x kubejs:chitinsteel_rib', 'kubejs:chitinsteel_spine'], 'biomancy:injector', 'biomancy:tools', 100)
    event.recipes.biomancy.bio_forging(['chestcavity:mana_reactor', '4x kubejs:dense_muscle', '2x industrialforegoing:pink_slime_ingot', '4x kubejs:chitinsteel_rib', '8x biomancy:exotic_dust'], 'biomancy:extractor', 'biomancy:tools', 100)
    event.recipes.biomancy.bio_forging(['chestcavity:mana_reactor', '8x kubejs:dense_muscle', '4x kubejs:mineral_brick', '4x kubejs:chitinsteel_rib', '20x biomancy:acid_extract'], 'biomancy:caustic_gunblade', 'biomancy:tools', 100)
    event.recipes.biomancy.bio_forging(['chestcavity:mana_reactor', '12x kubejs:dense_muscle', '2x biomancy:living_flesh', '4x kubejs:chitinsteel_rib', '4x biomancy:volatile_gland'], 'biomancy:impaler', 'biomancy:tools', 100)
    event.recipes.biomancy.bio_forging(['chestcavity:mana_reactor', '4x kubejs:dense_muscle', '8x kubejs:mineral_brick', '32x biomancy:tough_fibers', '8x biomancy:mob_fang'], 'biomancy:thorn_shield', 'biomancy:tools', 100)
    event.recipes.biomancy.bio_forging(['chestcavity:mana_reactor', '4x kubejs:dense_muscle', '4x kubejs:mineral_brick', '16x biomancy:tough_fibers', '4x biomancy:mob_claw'], 'biomancy:ravenous_claws', 'biomancy:tools', 100)

    event.recipes.biomancy.bio_forging(['biomancy:mob_fang', '2x biomancy:flesh_bits', 'biomancy:elastic_fibers'], '4x biomancy:maw_hopper', 'biomancy:machines', 20)
    event.recipes.biomancy.bio_forging(['3x biomancy:flesh_bits', 'biomancy:elastic_fibers'], 'biomancy:tongue', 'biomancy:machines', 5)
    event.recipes.biomancy.bio_forging(['8x biomancy:flesh_bits', '4x biomancy:bone_fragments', 'biomancy:impermeable_membrane', '2x biomancy:elastic_fibers'], 'biomancy:fleshkin_chest', 'biomancy:misc', 25)
    event.recipes.biomancy.bio_forging(['biomancy:gellant', '2x biomancy:flesh_bits', 'biomancy:elastic_fibers'], '3x biomancy:active_muscle', 'biomancy:misc', 10)
    event.recipes.biomancy.bio_forging(['biomancy:impermeable_membrane', '4x biomancy:flesh_bits', '4x biomancy:hormone_secretion', 'minecraft:phantom_membrane'], 'biomancy:chrysalis', 'biomancy:misc', 15)
    event.recipes.biomancy.bio_forging(['biomancy:impermeable_membrane', '4x biomancy:flesh_bits', '2x biomancy:tough_fibers'], 'biomancy:storage_sac', 'biomancy:misc', 20)
    event.recipes.biomancy.bio_forging(['biomancy:mob_fang', '2x biomancy:flesh_bits', 'biomancy:tough_fibers'], '4x biomancy:flesh_spike', 'biomancy:blocks', 5)
    event.recipes.biomancy.bio_forging(['biomancy:mob_gland', 'biomancy:impermeable_membrane', '2x biomancy:flesh_bits', '2x biomancy:elastic_fibers'], '8x thermal:florb', 'biomancy:tools', 10)
    event.recipes.biomancy.bio_forging(['3x biomancy:gellant', '3x biomancy:elastic_fibers', '2x biomancy:tough_fibers'], '4x biomancy:impermeable_membrane', 'biomancy:blocks', 5)
    event.recipes.biomancy.bio_forging(['biomancy:impermeable_membrane', '2x biomancy:elastic_fibers', '2x biomancy:tough_fibers'], '3x minecraft:phantom_membrane', 'biomancy:components', 30)
})